### ISSUE TITLE
Thermal Printer Discontinued

### ISSUE THREAD

**Issue by ashleymcnamara** [lastcoolnameleft/baiiab#6]
The Adafruit thermal printer has been discontinued, and I haven't been able to find a comparable alternative. Do you have any suggestions? Would you consider updating the parts list in the README to reflect this change? It might help others in their search for alternatives.

**Comment by lastcoolnameleft** [comment]
I hit this exact same problem when trying to build a backup for KubeCon EU!  Adafruit is no longer sourcing that model anymore; however, I found this one which I ordered and has been compatible for me.  (I plugged it in without any additional code changes). FYI, it's shipped from China.

https://www.seeedstudio.com/Embedded-Thermal-Printer-p-1621.html

Thanks for the heads up as I'll update the README.
